theme = "catppuccin_macchiato"

[editor]
bufferline = "multiple"
true-color = true
line-number = "relative"
insert-final-newline = false
   
[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding", "file-line-ending"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "│"
render = true

[editor.file-picker]
git-ignore = false

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true
# allow shift+x to reduce the size of an x selection

[keys.normal]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

# For Kakoune like config
S-left = "extend_char_left"
S-right = "extend_char_right"
S-up = "extend_line_up"
S-down = "extend_line_down"

"#" = "toggle_comments"
C-c = "no_op"
q = { q = "wclose" }
"space" = { "space" = "keep_primary_selection",  "q" = ":buffer-close" }
"esc" = [ "normal_mode", ":format" , ":write" ] # For quick saving

A-o = "add_newline_below"
A-O = [ "open_above", "normal_mode" ] # Doesn't work.

# Windows-like movement
C-left = [ "move_prev_word_start", "move_char_left", "move_char_right" ]
C-right = [ "move_next_word_start", "move_char_left", "move_char_right" ]

"ret" = ":write"
"C-q" = ":quit!"

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.insert]
C-backspace = "delete_word_backward"

# Windows-like movement (again)
C-left = [ "move_prev_word_start", "move_char_left", "move_char_right" ]
C-right = [ "move_next_word_start", "move_char_left", "move_char_right" ]