#[shell]
#args = ['--login']
#program = "/usr/bin/fish"

[cursor]
style = "Beam"

[font]
size = 8.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.98

[window.padding]
x = 20
y = 20

[window.dimensions]
columns = 140
lines = 35

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
