theme:
  lightTheme: false
  activeBorderColor:
    - "#89b4fa"
    - bold
  inactiveBorderColor:
    - "#a6adc8"
  optionsTextColor:
    - "#89b4fa"
  selectedLineBgColor:
    - "#313244"
  selectedRangeBgColor:
    - "#45475a"
  cherryPickedCommitBgColor:
    - "#45475a"
  cherryPickedCommitFgColor:
    - "#f5e0dc"
  unstagedChangesColor:
    - "#f38ba8"
  defaultFgColor:
    - "#cdd6f4"
  searchingActiveBorderColor:
    - "#f9e2af"
